package com.ncc.aif;

import org.apache.jena.rdf.model.Resource;
import org.apache.jena.rdf.model.ResourceFactory;

// WARNING. This is a Generated File.  Please do not edit.
// This class contains Variables generated from Ontologies using the OntologyGeneration Class
// Please refer to the README at src/main/java/com/ncc/aif/ont2javagen for more information
// Last Generated On: 02/05/2019 10:25:24
public final class SeedlingOntology {
    public static final Resource GeneralAffiliation_PersonAge = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#GeneralAffiliation.PersonAge");
    public static final Resource Justice_Fine = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Fine");
    public static final Resource Personnel_StartPosition = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Personnel.StartPosition");
    public static final Resource Movement_TransportArtifact = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Movement.TransportArtifact");
    public static final Resource Location = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Location");
    public static final Resource Justice_ArrestJail = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.ArrestJail");
    public static final Resource Life_Marry = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Life.Marry");
    public static final Resource Justice_ChargeIndict = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.ChargeIndict");
    public static final Resource Age = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Age");
    public static final Resource Contact_Meet = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Contact.Meet");
    public static final Resource Contact_Correspondence = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Contact.Correspondence");
    public static final Resource Government_Agreements = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Government.Agreements");
    public static final Resource GeneralAffiliation_OPRA = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#GeneralAffiliation.OPRA");
    public static final Resource Justice_Acquit = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Acquit");
    public static final Resource URL = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#URL");
    public static final Resource Physical_Resident = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Physical.Resident");
    public static final Resource GeneralAffiliation_Sponsorship = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#GeneralAffiliation.Sponsorship");
    public static final Resource GeneralAffiliation_APORA = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#GeneralAffiliation.APORA");
    public static final Resource Justice_Sue = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Sue");
    public static final Resource Business_End = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Business.End");
    public static final Resource Government_Vote = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Government.Vote");
    public static final Resource Physical_OrganizationLocationOrigin = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Physical.OrganizationLocationOrigin");
    public static final Resource Weapon = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Weapon");
    public static final Resource Justice_Appeal = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Appeal");
    public static final Resource Life_Die = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Life.Die");
    public static final Resource Contact_Contact = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Contact.Contact");
    public static final Resource Justice_Pardon = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Pardon");
    public static final Resource FillerType = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#FillerType");
    public static final Resource Justice_Convict = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Convict");
    public static final Resource Transaction_Transaction = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Transaction.Transaction");
    public static final Resource PersonalSocial_RoleTitle = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#PersonalSocial.RoleTitle");
    public static final Resource PersonalSocial_Unspecified = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#PersonalSocial.Unspecified");
    public static final Resource PersonalSocial_Family = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#PersonalSocial.Family");
    public static final Resource Sentence = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Sentence");
    public static final Resource NumericalValue = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#NumericalValue");
    public static final Resource Movement_TransportPerson = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Movement.TransportPerson");
    public static final Resource Justice_Sentence = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Sentence");
    public static final Resource Conflict_Demonstrate = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Conflict.Demonstrate");
    public static final Resource Life_Divorce = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Life.Divorce");
    public static final Resource Conflict_Attack = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Conflict.Attack");
    public static final Resource Money = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Money");
    public static final Resource Transaction_TransferOwnership = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Transaction.TransferOwnership");
    public static final Resource Personnel_EndPosition = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Personnel.EndPosition");
    public static final Resource GeopoliticalEntity = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#GeopoliticalEntity");
    public static final Resource OrganizationAffiliation_Ownership = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#OrganizationAffiliation.Ownership");
    public static final Resource PartWhole_Membership = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#PartWhole.Membership");
    public static final Resource Life_BeBorn = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Life.BeBorn");
    public static final Resource Time = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Time");
    public static final Resource Contact_Broadcast = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Contact.Broadcast");
    public static final Resource Government_Legislate = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Government.Legislate");
    public static final Resource Business_Merge = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Business.Merge");
    public static final Resource Existence_DamageDestroy = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Existence.DamageDestroy");
    public static final Resource OrganizationAffiliation_Founder = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#OrganizationAffiliation.Founder");
    public static final Resource Title = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Title");
    public static final Resource Ballot = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Ballot");
    public static final Resource Inspection_Artifact = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Inspection.Artifact");
    public static final Resource Person = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Person");
    public static final Resource Facility = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Facility");
    public static final Resource Justice_Extradite = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Extradite");
    public static final Resource Business_Start = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Business.Start");
    public static final Resource OrganizationAffiliation_Leadership = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#OrganizationAffiliation.Leadership");
    public static final Resource Business_DeclareBankruptcy = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Business.DeclareBankruptcy");
    public static final Resource Sides = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Sides");
    public static final Resource Justice_Execute = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Execute");
    public static final Resource Transaction_TransferMoney = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Transaction.TransferMoney");
    public static final Resource Personnel_Nominate = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Personnel.Nominate");
    public static final Resource Manufacture_Artifact = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Manufacture.Artifact");
    public static final Resource Justice_TrialHearing = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.TrialHearing");
    public static final Resource OrganizationAffiliation_InvestorShareholder = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#OrganizationAffiliation.InvestorShareholder");
    public static final Resource OrganizationAffiliation_StudentAlum = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#OrganizationAffiliation.StudentAlum");
    public static final Resource Justice_Investigate = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.Investigate");
    public static final Resource Life_Injure = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Life.Injure");
    public static final Resource Physical_OrganizationHeadquarter = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Physical.OrganizationHeadquarter");
    public static final Resource PersonalSocial_Business = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#PersonalSocial.Business");
    public static final Resource GeneralAffiliation_MORE = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#GeneralAffiliation.MORE");
    public static final Resource Personnel_Elect = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Personnel.Elect");
    public static final Resource Organization = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Organization");
    public static final Resource Inspection_People = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Inspection.People");
    public static final Resource Transaction_TransferControl = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Transaction.TransferControl");
    public static final Resource OrganizationAffiliation_EmploymentMembership = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#OrganizationAffiliation.EmploymentMembership");
    public static final Resource Results = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Results");
    public static final Resource Commodity = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Commodity");
    public static final Resource Vehicle = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Vehicle");
    public static final Resource PartWhole_Subsidiary = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#PartWhole.Subsidiary");
    public static final Resource Law = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Law");
    public static final Resource Crime = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Crime");
    public static final Resource Justice_ReleaseParole = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Justice.ReleaseParole");
    public static final Resource Physical_LocatedNear = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Physical.LocatedNear");
    public static final Resource Measurement_Count = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Measurement.Count");
    public static final Resource Government_Spy = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#Government.Spy");
    public static final Resource GeneralAffiliation_OrganizationWebsite = ResourceFactory.createResource("https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#GeneralAffiliation.OrganizationWebsite");
}
