package com.ncc.aif;

import org.apache.jena.rdf.model.Resource;
import org.apache.jena.rdf.model.ResourceFactory;
// WARNING. This is a Generated File. Please do not edit.
// This class contains variables generated from SHACL files using the OntologyGeneration class
// Please refer to the README at java/src/main/java/com/ncc/aif/ont2javagen for more information
// Last generated on: 01/21/2022 11:28:49
public final class ShaclShapes {
    public static final String NS = InterchangeOntology.NAMESPACE;
    public static final Resource AllKEsReferencedShape = ResourceFactory.createResource(NS + "AllKEsReferencedShape");
    public static final Resource AssociatedKEsEntityPrototypeRequireHandle = ResourceFactory.createResource(NS + "AssociatedKEsEntityPrototypeRequireHandle");
    public static final Resource AudioJustificationShape = ResourceFactory.createResource(NS + "AudioJustificationShape");
    public static final Resource BoundingBoxPropertyShape = ResourceFactory.createResource(NS + "BoundingBoxPropertyShape");
    public static final Resource BoundingBoxShape = ResourceFactory.createResource(NS + "BoundingBoxShape");
    public static final Resource ClaimComponentShape = ResourceFactory.createResource(NS + "ClaimComponentShape");
    public static final Resource ClaimShape = ResourceFactory.createResource(NS + "ClaimShape");
    public static final Resource ClusterMembersSameAsBaseClass = ResourceFactory.createResource(NS + "ClusterMembersSameAsBaseClass");
    public static final Resource ClusterMembersShape = ResourceFactory.createResource(NS + "ClusterMembersShape");
    public static final Resource ClusterMembershipShape = ResourceFactory.createResource(NS + "ClusterMembershipShape");
    public static final Resource ClusterShape = ResourceFactory.createResource(NS + "ClusterShape");
    public static final Resource CompoundJustificationMinimum = ResourceFactory.createResource(NS + "CompoundJustificationMinimum");
    public static final Resource CompoundJustificationShape = ResourceFactory.createResource(NS + "CompoundJustificationShape");
    public static final Resource CompoundJustificationTypes = ResourceFactory.createResource(NS + "CompoundJustificationTypes");
    public static final Resource ConfidencePropertyShape = ResourceFactory.createResource(NS + "ConfidencePropertyShape");
    public static final Resource ConfidenceShape = ResourceFactory.createResource(NS + "ConfidenceShape");
    public static final Resource ConfidenceValueRange = ResourceFactory.createResource(NS + "ConfidenceValueRange");
    public static final Resource ContentGraphShape = ResourceFactory.createResource(NS + "ContentGraphShape");
    public static final Resource DependsOnHypothesisPropertyShape = ResourceFactory.createResource(NS + "DependsOnHypothesisPropertyShape");
    public static final Resource EdgeJustificationCompound = ResourceFactory.createResource(NS + "EdgeJustificationCompound");
    public static final Resource EdgeJustificationCount = ResourceFactory.createResource(NS + "EdgeJustificationCount");
    public static final Resource EntityShape = ResourceFactory.createResource(NS + "EntityShape");
    public static final Resource EntitySubclass = ResourceFactory.createResource(NS + "EntitySubclass");
    public static final Resource EntityTypeShape = ResourceFactory.createResource(NS + "EntityTypeShape");
    public static final Resource EventArgumentShape = ResourceFactory.createResource(NS + "EventArgumentShape");
    public static final Resource EventArgumentSubclass = ResourceFactory.createResource(NS + "EventArgumentSubclass");
    public static final Resource EventRelationShape = ResourceFactory.createResource(NS + "EventRelationShape");
    public static final Resource EventSubclass = ResourceFactory.createResource(NS + "EventSubclass");
    public static final Resource EventTypeShape = ResourceFactory.createResource(NS + "EventTypeShape");
    public static final Resource HandlePropertyShape = ResourceFactory.createResource(NS + "HandlePropertyShape");
    public static final Resource HypothesisEntityPrototypeRequireHandle = ResourceFactory.createResource(NS + "HypothesisEntityPrototypeRequireHandle");
    public static final Resource HypothesisEventRelationPrototypeImportanceRequiredShape = ResourceFactory.createResource(NS + "HypothesisEventRelationPrototypeImportanceRequiredShape");
    public static final Resource HypothesisShape = ResourceFactory.createResource(NS + "HypothesisShape");
    public static final Resource ImageJustificationShape = ResourceFactory.createResource(NS + "ImageJustificationShape");
    public static final Resource ImportancePropertyShape = ResourceFactory.createResource(NS + "ImportancePropertyShape");
    public static final Resource ImportanceRequiredShape = ResourceFactory.createResource(NS + "ImportanceRequiredShape");
    public static final Resource InformativeJustificationMembersShape = ResourceFactory.createResource(NS + "InformativeJustificationMembersShape");
    public static final Resource InformativeJustificationMembersUniqueParentDoc = ResourceFactory.createResource(NS + "InformativeJustificationMembersUniqueParentDoc");
    public static final Resource InformativeJustificationPropertyShape = ResourceFactory.createResource(NS + "InformativeJustificationPropertyShape");
    public static final Resource JsonContentPropertyShape = ResourceFactory.createResource(NS + "JsonContentPropertyShape");
    public static final Resource JustificationPropertyShape = ResourceFactory.createResource(NS + "JustificationPropertyShape");
    public static final Resource JustificationSourceDocumentShape = ResourceFactory.createResource(NS + "JustificationSourceDocumentShape");
    public static final Resource KEsMustBeReferenced = ResourceFactory.createResource(NS + "KEsMustBeReferenced");
    public static final Resource KeyFrameVideoJustificationShape = ResourceFactory.createResource(NS + "KeyFrameVideoJustificationShape");
    public static final Resource LDCTimeComponentShape = ResourceFactory.createResource(NS + "LDCTimeComponentShape");
    public static final Resource LDCTimePropertyShape = ResourceFactory.createResource(NS + "LDCTimePropertyShape");
    public static final Resource LDCTimeShape = ResourceFactory.createResource(NS + "LDCTimeShape");
    public static final Resource LinkAssertionShape = ResourceFactory.createResource(NS + "LinkAssertionShape");
    public static final Resource LinkPropertyShape = ResourceFactory.createResource(NS + "LinkPropertyShape");
    public static final Resource MutualExclusionAlternativeShape = ResourceFactory.createResource(NS + "MutualExclusionAlternativeShape");
    public static final Resource MutualExclusionConstraintShape = ResourceFactory.createResource(NS + "MutualExclusionConstraintShape");
    public static final Resource NamePropertyShape = ResourceFactory.createResource(NS + "NamePropertyShape");
    public static final Resource NumericPropertyShape = ResourceFactory.createResource(NS + "NumericPropertyShape");
    public static final Resource ObjectMustBeClustered = ResourceFactory.createResource(NS + "ObjectMustBeClustered");
    public static final Resource PreventHandleOnCluster = ResourceFactory.createResource(NS + "PreventHandleOnCluster");
    public static final Resource PreventInformativeJustificationCluster = ResourceFactory.createResource(NS + "PreventInformativeJustificationCluster");
    public static final Resource PreventMultiClusterPrototypeShape = ResourceFactory.createResource(NS + "PreventMultiClusterPrototypeShape");
    public static final Resource PreventNonClusterPrototypeMemberShape = ResourceFactory.createResource(NS + "PreventNonClusterPrototypeMemberShape");
    public static final Resource PrivateDataPropertyShape = ResourceFactory.createResource(NS + "PrivateDataPropertyShape");
    public static final Resource PrototypeShape = ResourceFactory.createResource(NS + "PrototypeShape");
    public static final Resource RdfStatementShape = ResourceFactory.createResource(NS + "RdfStatementShape");
    public static final Resource RelationArgumentShape = ResourceFactory.createResource(NS + "RelationArgumentShape");
    public static final Resource RelationArgumentSubclass = ResourceFactory.createResource(NS + "RelationArgumentSubclass");
    public static final Resource RelationSubclass = ResourceFactory.createResource(NS + "RelationSubclass");
    public static final Resource RelationTypeShape = ResourceFactory.createResource(NS + "RelationTypeShape");
    public static final Resource RequiredConfidencePropertyShape = ResourceFactory.createResource(NS + "RequiredConfidencePropertyShape");
    public static final Resource RequiredJustificationPropertyShape = ResourceFactory.createResource(NS + "RequiredJustificationPropertyShape");
    public static final Resource RestrictCompoundJustificationPropertyShape = ResourceFactory.createResource(NS + "RestrictCompoundJustificationPropertyShape");
    public static final Resource RestrictNameProperty = ResourceFactory.createResource(NS + "RestrictNameProperty");
    public static final Resource RestrictNumericProperty = ResourceFactory.createResource(NS + "RestrictNumericProperty");
    public static final Resource RestrictTextProperty = ResourceFactory.createResource(NS + "RestrictTextProperty");
    public static final Resource SentimentShape = ResourceFactory.createResource(NS + "SentimentShape");
    public static final Resource SharedJustificationShape = ResourceFactory.createResource(NS + "SharedJustificationShape");
    public static final Resource SharedTypeShape = ResourceFactory.createResource(NS + "SharedTypeShape");
    public static final Resource ShotVideoJustificationShape = ResourceFactory.createResource(NS + "ShotVideoJustificationShape");
    public static final Resource SystemPropertyShape = ResourceFactory.createResource(NS + "SystemPropertyShape");
    public static final Resource SystemShape = ResourceFactory.createResource(NS + "SystemShape");
    public static final Resource TextJustificationShape = ResourceFactory.createResource(NS + "TextJustificationShape");
    public static final Resource TextPropertyShape = ResourceFactory.createResource(NS + "TextPropertyShape");
    public static final Resource VideoJustificationShape = ResourceFactory.createResource(NS + "VideoJustificationShape");
}
